### PR TITLE
Use UMD. Now works in CommonJS when window.$ is undefined

### PR DESCRIPTION
**Pull request by callumacrae**
`window.$` is undefined because I'm using Browserify to load everything, and setting it is hacky. This fix adds [UMD](https://github.com/umdjs/umd) to this project :smile:

### CODE REVIEW

**Comment by paltman** [comment]
Thanks!

**Comment by callumacrae** [comment]
Awesome :) how long will it be until this is in a release?

**Comment by callumacrae** [comment]
@paltman Hey, any update on releasing this? Could really use it, it's the last thing stopping me from getting rid of my `window.jQuery` hack!

**Comment by paltman** [comment]
@callumacrae I just published [0.13.0](https://github.com/eldarion/eldarion-ajax/releases/tag/0.13.0). It's not showing up on npmjs.org yet, but I assume that is just some caching.

**Comment by callumacrae** [comment]
It's showing for me. Thanks! :smile:

**Pull request merged**
